# fly.toml file generated for trending-arbitrage-app on 2023-03-28T14:57:59+07:00

app = "trending-arbitrage-app"
primary_region = "sin"

[[statics]]
  guest_path = "/myapp/public"
  url_prefix = "/"
