default: &default
  host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  pool: <%= ENV["DB_POOL"] || 5 %>
  username: <%= ENV["DB_USERNAME"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>


production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: trending-arbitrage-app-production
  port: 5432

development:
  <<: *default
  adapter: mysql2
  database: trending-arbitrage-app-development
  port: 3306
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: true

test:
  <<: *default
  adapter: mysql2
  database: trending-arbitrage-app-test
  username: <%= ENV["DB_USERNAME"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: true
