:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 25 %>
:queues:
  - critical
  - default
  - low
:scheduler:
  :dynamic: true
  :enabled: true
  :schedule:
    pull_all_currencies:
      every: "1d"
      queue: low
      class: PullAllCurrenciesJob